### ISSUE TITLE
Set up HTTPS

### ISSUE THREAD

**Issue by filips123** [browserify/browserify-website#55]
SSL certificate for http://browserify.org/ is valid only for GitHub's domains.

You should setup HTTPS in GitHub's repository settings or with an external provider like Cloudflare. You should also setup HTTP to HTTPS redirection.

**Comment by malobre** [comment]
To fix this the `A` dns record should be replaced with a `CNAME` to `browserify.github.io.`

**Comment by NexusXe** [comment]
No SSL? Really? This should really be expedited, especially on a website like this which has installation directions that could potentially be intercepted by a middleman.

**Comment by pkrumins** [comment]
@malobre - can you confirm these actions:

1) Delete the old A record that currently points to 192.30.252.153
2) Add a new CNAME record with the value browserify.github.io (or is it browserify-website.github.io)?

If I visit https://browserify.github.io it doesn't work. Also https://browserify-website.github.io doesn't work. Let me know what else I should do to make it work.

**Comment by malobre** [comment]
Things seems to have changed since my last message, and I can't see why it isn't working with the current setup.

Could you try removing and re-adding the custom domain in `Settings > Pages > Custom Domain` ?
This should retrigger the SSL certificate obtention mechanism.

(Also, the correct URI seems to be http://browserify.github.io/browserify-website, it redirect to the custom domain.)

**Comment by malobre** [comment]
![image](https://user-images.githubusercontent.com/1368457/118633189-7e4dae00-b7d1-11eb-8d1a-07f2b51e6386.png)
🎉🎉🎉

**Comment by pkrumins** [comment]
Thanks everyone!
